const nodemailer = require("nodemailer");

var transport = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  auth: {
    user: process.env.SMTP_USER, // generated by Mailtrap
    pass: process.env.SMTP_PASS, // generated by Mailtrap
  },
  debug: true, // show debug output
  // logger: true, // log information in console
});

module.exports = transport;
